apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 4
  labels:
    run: class-course
  name: class-course
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: class-course
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: class-course
    spec:
      containers:
      - image: gcr.io/my-project-1531888882785/class-course
        imagePullPolicy: Always
        name: class-course
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2018-12-20T05:24:04Z
    lastUpdateTime: 2018-12-20T05:24:14Z
    message: ReplicaSet "class-course-5fff4696bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-12-21T00:37:45Z
    lastUpdateTime: 2018-12-21T00:37:45Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-12-20T06:28:48Z
  generation: 1
  labels:
    run: class-calendar
  name: class-calendar
  namespace: default
  resourceVersion: "15551"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/class-calendar
  uid: 8294a654-0420-11e9-bbb8-42010a800030
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: class-calendar
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: class-calendar
    spec:
      containers:
      - image: gcr.io/my-project-1531888882785/class-calendar
        imagePullPolicy: Always
        name: class-calendar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-12-20T06:28:48Z
    lastUpdateTime: 2018-12-20T06:28:48Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-12-20T06:28:48Z
    lastUpdateTime: 2018-12-20T06:29:00Z
    message: ReplicaSet "class-calendar-b9fd898b7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
